
import type { Course, AppEvent } from './types';

// This data is now used for seeding the database, not for direct display.
export const coursesToSeed: Omit<Course, 'id'>[] = [
    {
    title: 'Protocol and Crown Control Training Etiquette',
    description: 'Master the art of etiquette for formal and professional settings.',
    category: 'Hospitality',
    instructor: { name: 'Dr. Emily Post', avatarUrl: 'https://picsum.photos/seed/ins1/100/100', verified: true },
    rating: 4.9,
    reviews: 1530,
    duration: 4,
    level: 'All Levels',
    price: 150,
    originalPrice: 200,
    imageUrl: '/course1.jpeg',
    imageHint: 'formal dining setup',
  },
  {
    title: 'Cleaning and Maintenance Fundamentals',
    description: 'Learn industry standards for commercial and residential cleaning.',
    category: 'Facilities Management',
    instructor: { name: 'Mr. Don Aslett', avatarUrl: 'https://picsum.photos/seed/ins2/100/100', verified: false },
    rating: 4.7,
    reviews: 890,
    duration: 6,
    level: 'Beginner',
    price: 99,
    originalPrice: 149,
    imageUrl: '/course2.jpeg',
    imageHint: 'cleaning supplies',
  },
  {
    title: 'Book Keeping and Inventory Management',
    category: 'Business',
    description: 'Essential skills for managing finances and stock for small businesses.',
    instructor: { name: 'Ms. Rachel Cruz', avatarUrl: 'https://picsum.photos/seed/ins3/100/100', verified: true },
    rating: 4.8,
    reviews: 2100,
    duration: 8,
    level: 'Intermediate',
    price: 220,
    originalPrice: 280,
    imageUrl: '/course3.jpeg',
    imageHint: 'ledger and calculator',
  },
  {
    title: 'Fine Dining Etiquette & Service',
    category: 'Hospitality',
    description: 'Advanced techniques for fine dining service and guest experience.',
    instructor: { name: 'Mr. Will Guidara', avatarUrl: 'https://picsum.photos/seed/ins4/100/100', verified: true },
    rating: 4.9,
    reviews: 1800,
    duration: 5,
    level: 'Advanced',
    price: 350,
    originalPrice: 420,
    imageUrl: '/course4.jpeg',
    imageHint: 'fine dining restaurant',
  },
  {
    title: 'Professional House-Keeping',
    category: 'Facilities Management',
    description: 'Comprehensive training for professional housekeeping in the hotel industry.',
    instructor: { name: 'Ms. Marie Kondo', avatarUrl: 'https://picsum.photos/seed/ins5/100/100', verified: false },
    rating: 4.8,
    reviews: 1250,
    duration: 10,
    level: 'Intermediate',
    price: 180,
    imageUrl: '/course5.jpeg',
    imageHint: 'hotel room cleaning',
  },
  {
    title: 'Advanced Cleaning and Maintenance',
    category: 'Facilities Management',
    description: 'Specialized techniques for floor care, restoration, and sanitation.',
    instructor: { name: 'Mr. Don Aslett', avatarUrl: 'https://picsum.photos/seed/ins6/100/100', verified: false },
    rating: 4.6,
    reviews: 750,
    duration: 12,
    level: 'Advanced',
    price: 250,
    originalPrice: 300,
    imageUrl: '/course6.jpeg',
    imageHint: 'industrial cleaning machine',
  },
   {
    title: 'Customer Service Excellence',
    category: 'Business',
    description: 'Develop key skills for providing outstanding customer service.',
    instructor: { name: 'Mr. Shep Hyken', avatarUrl: 'https://picsum.photos/seed/ins7/100/100', verified: true },
    rating: 4.8,
    reviews: 2500,
    duration: 4,
    level: 'Beginner',
    price: 120,
    imageUrl: '/course7.jpeg',
    imageHint: 'customer service representative',
  },
];


export const eventsToSeed: Omit<AppEvent, 'id'>[] = [
  {
    title: 'Protocol and Crown Control Training Etiquette',
    category: 'Workshop',
    date: '2024-11-15',
    location: 'Virtual',
    price: 150,
    imageUrl: '/course1.jpeg',
    imageHint: 'formal dining setup',
    organizer: 'Etiquette Experts'
  },
  {
    title: 'Cleaning and Maintenance Fundamentals',
    category: 'Seminar',
    date: '2024-12-02',
    location: 'New York, NY',
    price: 99,
    imageUrl: '/course2.jpeg',
    imageHint: 'cleaning supplies',
    organizer: 'CleanCo'
  },
  {
    title: 'Book Keeping and Inventory Management',
    category: 'Webinar',
    date: '2024-11-20',
    location: 'Online',
    price: 220,
    imageUrl: '/course3.jpeg',
    imageHint: 'ledger and calculator',
    organizer: 'Biz Solutions'
  },
  {
    title: 'Fine Dining Etiquette & Service',
    category: 'Workshop',
    date: '2024-12-10',
    location: 'San Francisco, CA',
    price: 350,
    imageUrl: '/course4.jpeg',
    imageHint: 'fine dining restaurant',
    organizer: 'Hospitality Masters'
  },
];
