import type { Course, AppEvent } from './types';

/**
 * Seed datasets for /api/seed (dev-only admin endpoint).
 *
 * The courses below mirror the published Ashford & Gray Fusion Academy
 * catalogue and are written in the standardised programme format:
 *   Overview → Who This Is For → What You Will Learn (modules) →
 *   Duration → Certification → Career Opportunities → Apply CTA
 *
 * To load them into Mongo, sign in as admin and GET /api/seed.
 */

const ACADEMY_AVATAR = '/A & G2.png';
const FOUNDER_AVATAR = '/CEO Myne.jpg.jpeg';

const academyBoard = {
    name: 'Ashford & Gray Faculty',
    avatarUrl: ACADEMY_AVATAR,
    verified: true,
};

const founder = {
    name: 'Dr. Myne Wilfred',
    avatarUrl: FOUNDER_AVATAR,
    verified: true,
};

// Brand photography from /public — already curated to Ashford & Gray's
// Nigerian heritage aesthetic. Replace specific files in /public to refresh
// any single course image without re-seeding.
const IMG = {
    housekeeping: '/housekeeping_certificate.png',
    hospitality: '/hospitality_management_certificate.png',
    events: '/course1.jpeg',
    executive: '/course2.jpeg',
    globalRelations: '/course3.jpeg',
    diplomaHospitality: '/course4.jpeg',
    diplomaLeadership: '/course5.jpeg',
    diplomaBusiness: '/course6.jpeg',
    diplomaEvents: '/course7.jpeg',
    silentStandard: '/graduate-diploma.jpg',
};

export const coursesToSeed: Omit<Course, 'id' | 'progress'>[] = [
    // ===================================================================
    // CERTIFICATE PROGRAMS — 3 months · ₦450,000
    // ===================================================================
    {
        title: 'Housekeeping & Domestic Management',
        category: 'Certification',
        instructor: academyBoard,
        rating: 4.9,
        reviews: 124,
        duration: 12,
        level: 'Intermediate',
        price: 450000,
        currency: 'NGN',
        imageUrl: IMG.housekeeping,
        imageHint: 'Pristine luxury bedroom with crisp linens',
        status: 'published',
        description:
            'The Housekeeping & Domestic Management Certificate Programme at Ashford & Gray Fusion Academy is a professionally structured training designed to equip learners with practical, executive-level skills in housekeeping operations, domestic management, wardrobe coordination, and luxury service standards. The programme combines industry-based techniques with modern hospitality practices to prepare students for excellence in residential, hospitality, and executive service environments — hands-on knowledge in cleaning systems, hygiene protocols, wardrobe care, household coordination, client preference management, and luxury domestic operations. It is intentionally designed to reflect international hospitality standards while remaining practical, applicable, and career-focused.',
        curriculum: [
            'Module 1: Foundations of Housekeeping',
            'Module 2: Domestic Operations & Client Service',
            'Module 3: Wardrobe & Luxury Garment Management',
            'Module 4: Personal Organisation & Executive Wardrobe Systems',
        ],
        whoFor: [
            'Aspiring housekeepers and domestic professionals',
            'Hospitality and hotel operations personnel',
            'Estate and residence managers',
            'Personal assistants and executive aides',
            'Caregivers and home management professionals',
            'Individuals seeking international-standard domestic management skills',
            'Entrepreneurs interested in luxury cleaning or home service businesses',
            'Professionals looking to improve organisation and household management expertise',
        ],
        learningOutcomes: [
            {
                module: 'Module 1: Foundations of Housekeeping',
                topics: [
                    'Introduction to Housekeeping',
                    'Principles of Professional Cleaning',
                    'Cleaning Techniques & Sanitisation',
                    'Bed Making & Room Setup',
                    'Deep Cleaning Procedures',
                    'Maintenance Coordination',
                    'Inventory & Storage Management',
                ],
            },
            {
                module: 'Module 2: Domestic Operations & Client Service',
                topics: [
                    'Hygiene & Safety Protocols',
                    'Managing Household Staff',
                    'Understanding Client Preferences',
                    'Professional Conduct & Confidentiality',
                    'Emergency Response & Crisis Handling',
                    'Household Organisation Systems',
                    'Final Practical Assessment',
                ],
            },
            {
                module: 'Module 3: Wardrobe & Luxury Garment Management',
                topics: [
                    'Introduction to Wardrobe Management',
                    'Fabric Care & Cleaning Techniques',
                    'Luxury Garment Handling',
                    'Ironing, Pressing & Folding Standards',
                    'Stain Removal Techniques',
                    'Dry Cleaning Coordination',
                ],
            },
            {
                module: 'Module 4: Personal Organisation & Executive Wardrobe Systems',
                topics: [
                    'Organising Closets & Storage Spaces',
                    'Shoe & Leather Care',
                    'Travel Wardrobe Management',
                    'Budgeting & Inventory Management',
                    'Wardrobe Documentation Systems',
                    'Final Practical & Competency Evaluation',
                ],
            },
        ],
        certificationDetails: [
            'Professional Certificate in Housekeeping & Domestic Management',
            'Practical Competency Assessment Report',
            'Executive Skills Development Recognition',
            'Ashford & Gray Fusion Academy Certification of Completion',
            'Eligible: professional recommendation references',
            'Eligible: internship or placement opportunities',
            'Eligible: advanced executive domestic management training pathways',
        ],
        careerOpportunities: [
            'Professional Housekeepers',
            'Executive Housekeepers',
            'Domestic Managers',
            'Residence or Estate Assistants',
            'Wardrobe Managers',
            'Hotel Housekeeping Supervisors',
            'Luxury Home Service Professionals',
            'Personal Household Coordinators',
            'Hospitality Support Executives',
            'Cleaning & Domestic Service Entrepreneurs',
        ],
    },

    {
        title: 'Hospitality Management',
        category: 'Certification',
        instructor: academyBoard,
        rating: 4.9,
        reviews: 198,
        duration: 12,
        level: 'Intermediate',
        price: 450000,
        currency: 'NGN',
        imageUrl: IMG.hospitality,
        imageHint: 'Refined hotel lobby with concierge presence',
        status: 'published',
        description:
            'The Hospitality Management Certificate Programme is a premium professional training designed to develop highly skilled hospitality professionals equipped to operate within luxury, corporate, executive, and international service environments. It combines the principles of hospitality excellence, executive service delivery, guest relations, protocol management, and luxury client experience into a structured, industry-focused curriculum. Participants gain practical knowledge in butlering, concierge services, VIP coordination, communication, customer retention, conflict resolution, and high-end hospitality operations. Built on global hospitality standards, the programme prepares learners to confidently manage guests, clients, events, and service operations with professionalism, discretion, and precision.',
        curriculum: [
            'Module 1: Foundations of Hospitality & Executive Service',
            'Module 2: Communication, Coordination & Client Relations',
            'Module 3: Luxury Hospitality Operations',
            'Module 4: Guest Retention & Crisis Management',
        ],
        whoFor: [
            'Aspiring hospitality professionals',
            'Hotel and guest service personnel',
            'Front office and concierge staff',
            'Butlers and executive service providers',
            'Event and protocol officers',
            'Personal assistants and lifestyle managers',
            'Customer service professionals',
            'Entrepreneurs in hospitality and luxury service industries',
            'Individuals seeking international-standard hospitality training',
            'Professionals aiming to improve executive-level guest experience delivery',
        ],
        learningOutcomes: [
            {
                module: 'Module 1: Foundations of Hospitality & Executive Service',
                topics: [
                    'Role of a Butler & Concierge',
                    'Guest Services & Professional Protocol',
                    'Table Setting & Fine Dining Standards',
                    'Managing High-End Clients',
                    'Confidentiality & Professional Discretion',
                    'Luxury Service Etiquette',
                    'Professional Appearance & Conduct',
                ],
            },
            {
                module: 'Module 2: Communication, Coordination & Client Relations',
                topics: [
                    'Advanced Communication Skills',
                    'VIP Event Coordination',
                    'Travel & Lifestyle Management',
                    'Conflict Resolution Techniques',
                    'Service Recovery Systems',
                    'Managing Guest Expectations',
                    'Final Practical Assessment',
                ],
            },
            {
                module: 'Module 3: Luxury Hospitality Operations',
                topics: [
                    'Luxury Hospitality Foundations',
                    'Cultural Sensitivity & International Guest Relations',
                    'Personalised Guest Experience Management',
                    'Effective Hospitality Communication',
                    'Handling Complaints Professionally',
                    'Service Standards & Operational Excellence',
                ],
            },
            {
                module: 'Module 4: Guest Retention & Crisis Management',
                topics: [
                    'Customer Retention Strategies',
                    'Upselling & Cross-Selling Techniques',
                    'Case Studies in Guest Relations',
                    'Hospitality Crisis Management',
                    'Reputation & Brand Protection',
                    'Certification & Final Competency Assessment',
                ],
            },
        ],
        certificationDetails: [
            'Professional Certificate in Hospitality Management',
            'Executive Hospitality Skills Recognition',
            'Practical Competency Assessment Report',
            'Ashford & Gray Fusion Academy Certification of Completion',
            'Eligible: professional recommendation references',
            'Eligible: hospitality internship opportunities',
            'Eligible: advanced executive hospitality specialisation pathways',
        ],
        careerOpportunities: [
            'Hospitality Managers',
            'Guest Relations Officers',
            'Concierge Professionals',
            'Executive Butlers',
            'Front Office Supervisors',
            'VIP Service Coordinators',
            'Protocol Officers',
            'Lifestyle & Travel Assistants',
            'Event Hospitality Coordinators',
            'Customer Experience Executives',
            'Luxury Hospitality Consultants',
        ],
    },

    {
        title: 'Events & Protocol Management',
        category: 'Certification',
        instructor: academyBoard,
        rating: 4.8,
        reviews: 156,
        duration: 12,
        level: 'Intermediate',
        price: 450000,
        currency: 'NGN',
        imageUrl: IMG.events,
        imageHint: 'Ballroom prepared for a formal evening event',
        status: 'published',
        description:
            'The Events & Protocol Management Certificate Programme is a comprehensive professional training designed to equip learners with the strategic, operational, and executive-level skills required to successfully manage events, ceremonies, corporate functions, VIP engagements, and protocol operations. It blends modern event management practices with international protocol standards, preparing participants to confidently coordinate high-level events with precision, professionalism, discretion, and excellence. Learners gain practical knowledge in event planning, vendor coordination, budgeting, security management, crisis communication, crowd control, official protocol, and high-profile guest relations. Designed to meet global industry expectations, the programme focuses on developing professionals capable of delivering seamless experiences within corporate, diplomatic, hospitality, entertainment, and executive environments.',
        curriculum: [
            'Module 1: Foundations of Event Planning & Coordination',
            'Module 2: Event Operations & Crisis Management',
            'Module 3: Protocol, Etiquette & High-Profile Engagement',
            'Module 4: International Protocol & Strategic Coordination',
        ],
        whoFor: [
            'Aspiring event planners and coordinators',
            'Hospitality and protocol professionals',
            'Corporate event managers',
            'Protocol officers and executive aides',
            'Wedding and social event planners',
            'Government and diplomatic support personnel',
            'Public relations and communications professionals',
            'Security and crowd management personnel',
            'Entrepreneurs in the events industry',
            'Individuals seeking international-standard event and protocol training',
        ],
        learningOutcomes: [
            {
                module: 'Module 1: Foundations of Event Planning & Coordination',
                topics: [
                    'Introduction to Event Planning',
                    'Venue Selection & Event Design',
                    'Vendor Coordination & Contract Management',
                    'Event Budgeting & Financial Planning',
                    'VIP & Celebrity Event Management',
                    'Event Scheduling & Logistics',
                    'Professional Event Documentation',
                ],
            },
            {
                module: 'Module 2: Event Operations & Crisis Management',
                topics: [
                    'Security & Risk Management',
                    'Crisis Communication Strategies',
                    'Event Marketing & Promotion',
                    'Event Execution & Coordination',
                    'Team Management During Events',
                    'Post-Event Evaluation & Reporting',
                    'Final Practical Assessment',
                ],
            },
            {
                module: 'Module 3: Protocol, Etiquette & High-Profile Engagement',
                topics: [
                    'Introduction to Protocol & Etiquette',
                    'Cultural Sensitivities & International Standards',
                    'High-Profile Guest Management',
                    'Crowd Psychology & Behavioural Management',
                    'Security & Emergency Protocols',
                    'Executive Conduct & Professionalism',
                ],
            },
            {
                module: 'Module 4: International Protocol & Strategic Coordination',
                topics: [
                    'Official Documentation & Event Briefing',
                    'Crisis Handling & Decision Making',
                    'International Protocol Procedures',
                    'Case Studies in Successful Protocol Management',
                    'Reputation Protection & Stakeholder Relations',
                    'Final Practical & Competency Assessment',
                ],
            },
        ],
        certificationDetails: [
            'Professional Certificate in Events & Protocol Management',
            'Executive Event Coordination Skills Recognition',
            'Practical Competency Assessment Report',
            'Ashford & Gray Fusion Academy Certification of Completion',
            'Eligible: professional recommendation references',
            'Eligible: event internship or industry placement opportunities',
            'Eligible: advanced executive protocol specialisation pathways',
        ],
        careerOpportunities: [
            'Event Planners & Coordinators',
            'Protocol Officers',
            'Corporate Event Managers',
            'Wedding & Social Event Consultants',
            'VIP Liaison Officers',
            'Celebrity & Executive Event Coordinators',
            'Public Relations & Event Support Executives',
            'Government & Diplomatic Event Assistants',
            'Conference & Convention Coordinators',
            'Security & Crowd Management Supervisors',
            'Entrepreneurs in Event & Hospitality Services',
        ],
    },

    {
        title: 'Executive Assistant Management',
        category: 'Certification',
        instructor: academyBoard,
        rating: 4.9,
        reviews: 173,
        duration: 12,
        level: 'Intermediate',
        price: 450000,
        currency: 'NGN',
        imageUrl: IMG.executive,
        imageHint: 'Executive office workspace and calendar planning',
        status: 'published',
        description:
            'The Executive Assistant Management Certificate Programme is a high-level professional training designed to prepare participants for strategic support roles within executive, corporate, diplomatic, hospitality, and luxury service environments. It equips learners with the practical, organisational, communication, and leadership skills required to effectively manage executives, high-net-worth individuals, business operations, schedules, travel coordination, confidential communication, and corporate engagements. Participants also gain insight into luxury concierge services, lifestyle management, protocol, executive decision support, and crisis handling. Combining administrative excellence with executive-level professionalism, the programme is structured to develop highly competent professionals capable of operating with discretion, precision, and confidence in demanding environments.',
        curriculum: [
            'Module 1: VIP Concierge & Lifestyle Management',
            'Module 2: High-Net-Worth Client Management',
            'Module 3: Executive Assistance & Corporate Operations',
            'Module 4: Leadership Support & Strategic Administration',
        ],
        whoFor: [
            'Aspiring executive assistants and personal assistants',
            'Administrative and office professionals',
            'Executive secretaries and coordinators',
            'Lifestyle and concierge professionals',
            'Corporate support staff',
            'Hospitality and protocol officers',
            'Entrepreneurs offering executive support services',
            'Individuals working with high-profile clients or executives',
            'Professionals seeking executive-level organisational and communication skills',
            'Individuals seeking international-standard executive assistant training',
        ],
        learningOutcomes: [
            {
                module: 'Module 1: VIP Concierge & Lifestyle Management',
                topics: [
                    'Understanding VIP Concierge Services',
                    'Luxury Lifestyle Management',
                    'Personal Assistant Duties & Responsibilities',
                    'Exclusive Travel & Reservation Coordination',
                    'Personal Styling & Image Management',
                    'Professional Conduct & Service Excellence',
                    'Managing Executive Expectations',
                ],
            },
            {
                module: 'Module 2: High-Net-Worth Client Management',
                topics: [
                    'Managing High-Net-Worth Clients',
                    'Special Event Coordination',
                    'Confidentiality in VIP Services',
                    'Crisis Management in Executive Environments',
                    'Executive Communication Systems',
                    'Relationship Management & Client Retention',
                    'Final Practical Assessment',
                ],
            },
            {
                module: 'Module 3: Executive Assistance & Corporate Operations',
                topics: [
                    'Introduction to Executive Assistance',
                    'Professional Correspondence & Business Writing',
                    'Scheduling & Time Management',
                    'Business Travel Planning',
                    'Managing Corporate Events',
                    'Office Coordination & Administrative Systems',
                    'Executive Reporting Procedures',
                ],
            },
            {
                module: 'Module 4: Leadership Support & Strategic Administration',
                topics: [
                    'Leadership Support & Decision-Making',
                    'Data & File Management',
                    'Presentation & Public Speaking Skills',
                    'Conflict Resolution Techniques',
                    'Workplace Professionalism & Ethics',
                    'Final Project & Competency Evaluation',
                ],
            },
        ],
        certificationDetails: [
            'Professional Certificate in Executive Assistant Management',
            'Executive Administrative Skills Recognition',
            'Practical Competency Assessment Report',
            'Ashford & Gray Fusion Academy Certification of Completion',
            'Eligible: professional recommendation references',
            'Eligible: internship or executive placement opportunities',
            'Eligible: advanced executive leadership and administrative specialisation pathways',
        ],
        careerOpportunities: [
            'Executive Assistants',
            'Personal Assistants',
            'Executive Secretaries',
            'VIP Concierge Professionals',
            'Lifestyle Managers',
            'Administrative Coordinators',
            'Protocol & Executive Support Officers',
            'Corporate Office Managers',
            'Travel & Executive Logistics Coordinators',
            'Executive Event Support Professionals',
            'Business Support Consultants',
        ],
    },

    {
        title: 'Hospitality & Global Relationship Management',
        category: 'Certification',
        instructor: academyBoard,
        rating: 4.8,
        reviews: 142,
        duration: 12,
        level: 'Intermediate',
        price: 450000,
        currency: 'NGN',
        imageUrl: IMG.globalRelations,
        imageHint: 'International business handshake across cultures',
        status: 'published',
        description:
            'The Hospitality & Global Relationship Management Certificate Programme is a professionally designed training focused on developing globally minded professionals equipped with the skills required to navigate international business environments, diplomatic engagements, negotiation processes, and cross-cultural relationships. It blends hospitality excellence with international relations, business diplomacy, negotiation strategy, conflict management, and global communication practices. Participants gain practical knowledge in diplomatic protocol, international business ethics, mediation, workplace dispute resolution, and strategic relationship management. Structured to meet international standards, the programme prepares learners to confidently operate within corporate, diplomatic, hospitality, governmental, and multinational environments where professionalism, negotiation, and relationship management are critical.',
        curriculum: [
            'Module 1: Global Business & International Relations',
            'Module 2: Diplomacy, Ethics & Crisis Management',
            'Module 3: Negotiation & Conflict Resolution',
            'Module 4: Advanced Negotiation & Global Engagement',
        ],
        whoFor: [
            'Hospitality and corporate professionals',
            'Diplomacy and protocol enthusiasts',
            'Executive assistants and administrators',
            'Business development professionals',
            'Entrepreneurs and business owners',
            'Government and public sector personnel',
            'Human resource and relationship managers',
            'Customer and client relations professionals',
            'Individuals seeking international business and negotiation skills',
            'Professionals aiming to improve cross-cultural communication and conflict management expertise',
        ],
        learningOutcomes: [
            {
                module: 'Module 1: Global Business & International Relations',
                topics: [
                    'Introduction to Global Business',
                    'Trade Policies & International Agreements',
                    'Diplomatic Protocols & Professional Etiquette',
                    'International Negotiation Strategies',
                    'Cross-Cultural Communication Skills',
                    'Relationship Management in Global Environments',
                    'International Business Communication',
                ],
            },
            {
                module: 'Module 2: Diplomacy, Ethics & Crisis Management',
                topics: [
                    'Case Studies in Diplomacy',
                    'Global Business Ethics',
                    'International Crisis Management',
                    'Strategic Decision-Making in Global Relations',
                    'Career Opportunities in Diplomacy & International Affairs',
                    'Leadership in Multicultural Environments',
                    'Final Project Assessment',
                ],
            },
            {
                module: 'Module 3: Negotiation & Conflict Resolution',
                topics: [
                    'Fundamentals of Negotiation',
                    'Mediation Strategies & Techniques',
                    'Conflict Resolution Frameworks',
                    'Handling Difficult People Professionally',
                    'Workplace Dispute Management',
                    'Emotional Intelligence in Negotiation',
                    'Communication During Conflict Situations',
                ],
            },
            {
                module: 'Module 4: Advanced Negotiation & Global Engagement',
                topics: [
                    'Cross-Cultural Negotiation',
                    'Business Contract Negotiation',
                    'Case Studies in Conflict Resolution',
                    'Stakeholder & Relationship Management',
                    'Final Negotiation Simulation',
                    'Professional Assessment & Certification',
                ],
            },
        ],
        certificationDetails: [
            'Professional Certificate in Hospitality & Global Relationship Management',
            'Negotiation & Conflict Resolution Skills Recognition',
            'Practical Competency Assessment Report',
            'Ashford & Gray Fusion Academy Certification of Completion',
            'Eligible: professional recommendation references',
            'Eligible: internship or placement opportunities',
            'Eligible: advanced diplomacy and executive relationship management specialisation pathways',
        ],
        careerOpportunities: [
            'Relationship Managers',
            'Hospitality & Guest Relations Executives',
            'Protocol & Diplomacy Officers',
            'Business Development Executives',
            'Corporate Communication Professionals',
            'Negotiation & Mediation Consultants',
            'Human Resource & Conflict Resolution Officers',
            'International Business Coordinators',
            'Customer Experience Managers',
            'Public Relations & Stakeholder Engagement Officers',
            'Executive Liaison Officers',
        ],
    },

    // ===================================================================
    // DIPLOMA PROGRAMS — 6 months · ₦950,000
    // ===================================================================
    {
        title: 'Diploma in Hospitality Management',
        category: 'Diploma',
        instructor: academyBoard,
        rating: 4.9,
        reviews: 87,
        duration: 24,
        level: 'Advanced',
        price: 950000,
        currency: 'NGN',
        imageUrl: IMG.diplomaHospitality,
        imageHint: 'Luxury hotel staff in formal service attire',
        status: 'published',
        description:
            'The Diploma in Hospitality Management is an advanced professional programme designed to develop highly competent hospitality professionals equipped with practical expertise, leadership capacity, and global service standards. It combines housekeeping operations, executive hospitality, guest relations, luxury service delivery, wardrobe management, protocol systems, and hospitality administration into a comprehensive learning experience tailored for today\'s evolving hospitality industry. Structured with a blend of theoretical knowledge and practical industry application, the programme prepares students to confidently manage hospitality environments, luxury guest experiences, executive residences, hotels, and high-end service operations with professionalism, discretion, and excellence. The curriculum is intentionally designed to reflect international hospitality standards while developing professionals capable of operating effectively within local and global hospitality environments.',
        curriculum: [
            'Module 1: Housekeeping & Domestic Operations',
            'Module 2: Executive Hospitality & Guest Relations',
            'Module 3: Luxury Hospitality & Customer Experience',
            'Module 4: Wardrobe & Executive Lifestyle Management',
        ],
        whoFor: [
            'Aspiring hospitality professionals and managers',
            'Hotel and guest service personnel',
            'Executive housekeepers and supervisors',
            'Butlers and concierge professionals',
            'Estate and residence managers',
            'Event and protocol professionals',
            'Entrepreneurs in hospitality and luxury service industries',
            'Individuals seeking international-standard hospitality education',
            'Professionals looking to upgrade their leadership and operational hospitality skills',
            'Individuals preparing for executive-level hospitality and service careers',
        ],
        learningOutcomes: [
            {
                module: 'Module 1: Housekeeping & Domestic Operations',
                topics: [
                    'Introduction to Housekeeping',
                    'Cleaning Techniques & Sanitisation',
                    'Bed Making & Room Setup',
                    'Deep Cleaning & Maintenance Procedures',
                    'Inventory & Storage Management',
                    'Hygiene Protocols & Safety Standards',
                    'Managing Household Staff',
                    'Understanding Client Preferences',
                    'Emergency Response Procedures',
                    'Practical Assessment',
                ],
            },
            {
                module: 'Module 2: Executive Hospitality & Guest Relations',
                topics: [
                    'Role of a Butler & Concierge',
                    'Guest Services & Professional Protocol',
                    'Table Setting & Fine Dining Standards',
                    'Managing High-End Clients',
                    'Confidentiality & Professional Discretion',
                    'Advanced Communication Skills',
                    'VIP Event Coordination',
                    'Travel & Lifestyle Management',
                    'Conflict Resolution Techniques',
                    'Final Practical Assessment',
                ],
            },
            {
                module: 'Module 3: Luxury Hospitality & Customer Experience',
                topics: [
                    'Luxury Hospitality Foundations',
                    'Cultural Sensitivity & International Guest Relations',
                    'Personalised Guest Experience Management',
                    'Professional Communication Skills',
                    'Handling Complaints Professionally',
                    'Customer Retention Strategies',
                    'Upselling & Cross-Selling Techniques',
                    'Case Studies in Guest Relations',
                    'Crisis Management in Hospitality',
                    'Certification Assessment',
                ],
            },
            {
                module: 'Module 4: Wardrobe & Executive Lifestyle Management',
                topics: [
                    'Introduction to Wardrobe Management',
                    'Fabric Care & Cleaning Techniques',
                    'Luxury Garment Handling',
                    'Ironing, Pressing & Folding Standards',
                    'Stain Removal & Dry Cleaning Coordination',
                    'Organising Closets & Storage Systems',
                    'Shoe & Leather Care',
                    'Travel Wardrobe Management',
                    'Budgeting & Inventory Management',
                    'Final Practical Evaluation',
                ],
            },
        ],
        certificationDetails: [
            'Diploma in Hospitality Management',
            'Professional Hospitality Competency Certification',
            'Executive Service & Guest Relations Recognition',
            'Practical Skills Assessment Report',
            'Ashford & Gray Fusion Academy Diploma Certification',
            'Eligible: internship and industry placement opportunities',
            'Eligible: executive hospitality specialisation pathways',
            'Eligible: professional recommendation references',
        ],
        careerOpportunities: [
            'Hospitality Managers',
            'Executive Housekeepers',
            'Guest Relations Managers',
            'Concierge Professionals',
            'Executive Butlers',
            'Residence & Estate Managers',
            'Front Office Supervisors',
            'Luxury Hospitality Coordinators',
            'VIP Service Executives',
            'Lifestyle & Travel Managers',
            'Hospitality Consultants',
            'Customer Experience Managers',
            'Hospitality Entrepreneurs',
        ],
    },

    {
        title: 'Diploma in Professional Development & Global Relations',
        category: 'Diploma',
        instructor: academyBoard,
        rating: 4.8,
        reviews: 76,
        duration: 24,
        level: 'Advanced',
        price: 950000,
        currency: 'NGN',
        imageUrl: IMG.diplomaLeadership,
        imageHint: 'Leadership boardroom and professional development',
        status: 'published',
        description:
            'The Diploma in Professional Development & Global Relations is a comprehensive professional programme designed to develop confident leaders, strategic communicators, globally minded professionals, and effective negotiators equipped to thrive within modern corporate, diplomatic, and international business environments. It combines leadership development, emotional intelligence, workplace professionalism, global relations, diplomacy, negotiation, and conflict management into a practical, industry-focused learning experience. Participants gain the knowledge, confidence, and strategic skills required to lead teams, manage professional relationships, communicate effectively across cultures, and navigate complex workplace and international environments with professionalism and authority. Built on international standards and executive-level training principles, the programme prepares learners for leadership, career advancement, global engagement, and professional excellence across multiple industries.',
        curriculum: [
            'Module 1: Leadership Development & Professional Excellence',
            'Module 2: Global Relations & International Engagement',
            'Module 3: Career Development & Workplace Readiness',
            'Module 4: Negotiation, Mediation & Conflict Management',
        ],
        whoFor: [
            'Emerging and aspiring leaders',
            'Corporate professionals and administrators',
            'Human resource and relationship managers',
            'Diplomacy and international relations enthusiasts',
            'Entrepreneurs and business executives',
            'Executive assistants and protocol officers',
            'Public relations and communication professionals',
            'Individuals seeking career advancement and leadership development',
            'Professionals interested in negotiation and conflict resolution',
            'Individuals preparing for global business and multicultural work environments',
        ],
        learningOutcomes: [
            {
                module: 'Module 1: Leadership Development & Professional Excellence',
                topics: [
                    'Leadership Theories & Leadership Styles',
                    'Emotional Intelligence & Self-Awareness',
                    'Team Leadership & Team Dynamics',
                    'Conflict Resolution Techniques',
                    'Strategic Decision Making',
                    'Time Management & Productivity',
                    'Understanding Corporate Culture',
                    'Leadership Case Studies',
                    'Ethical Leadership Principles',
                    'Leadership Simulation Exercises',
                ],
            },
            {
                module: 'Module 2: Global Relations & International Engagement',
                topics: [
                    'Introduction to Global Business',
                    'Trade Policies & International Agreements',
                    'Diplomatic Protocols & Professional Etiquette',
                    'International Negotiation Strategies',
                    'Cross-Cultural Communication Skills',
                    'Case Studies in Diplomacy',
                    'Global Business Ethics',
                    'International Crisis Management',
                    'Career Opportunities in Diplomacy & Global Relations',
                    'Final Project Assessment',
                ],
            },
            {
                module: 'Module 3: Career Development & Workplace Readiness',
                topics: [
                    'Career Planning & Goal Setting',
                    'Workplace Communication Skills',
                    'Resume & Cover Letter Writing',
                    'Professional Networking Strategies',
                    'Personal Branding & Executive Presence',
                    'Job Interview Techniques',
                    'Office Politics & Workplace Conflict Management',
                    'Ethics & Professional Conduct',
                    'Work-Life Balance Strategies',
                    'Final Career Plan Presentation',
                ],
            },
            {
                module: 'Module 4: Negotiation, Mediation & Conflict Management',
                topics: [
                    'Fundamentals of Negotiation',
                    'Mediation Strategies & Techniques',
                    'Conflict Resolution Frameworks',
                    'Handling Difficult People Professionally',
                    'Workplace Dispute Management',
                    'Cross-Cultural Negotiation',
                    'Business Contract Negotiation',
                    'Case Studies in Conflict Resolution',
                    'Final Negotiation Simulation',
                    'Assessment & Certification',
                ],
            },
        ],
        certificationDetails: [
            'Diploma in Professional Development & Global Relations',
            'Leadership & Negotiation Competency Certification',
            'Professional Communication & Global Relations Recognition',
            'Practical Skills Assessment Report',
            'Ashford & Gray Fusion Academy Diploma Certification',
            'Eligible: executive mentorship opportunities',
            'Eligible: internship and placement opportunities',
            'Eligible: leadership development recommendations',
            'Eligible: advanced professional specialisation pathways',
        ],
        careerOpportunities: [
            'Corporate Executives & Team Leaders',
            'Human Resource & Relationship Managers',
            'Diplomacy & Protocol Officers',
            'Negotiation & Conflict Resolution Specialists',
            'Corporate Communication Professionals',
            'Executive Administrators',
            'Leadership Development Coordinators',
            'Public Relations & Stakeholder Managers',
            'International Business Coordinators',
            'Professional Development Consultants',
            'Career & Workplace Coaches',
            'Mediation & Workplace Relations Officers',
        ],
    },

    {
        title: 'Diploma in Business Innovation & Entrepreneurship',
        category: 'Diploma',
        instructor: academyBoard,
        rating: 4.9,
        reviews: 102,
        duration: 24,
        level: 'Advanced',
        price: 950000,
        currency: 'NGN',
        imageUrl: IMG.diplomaBusiness,
        imageHint: 'Modern entrepreneurs collaborating at a strategy session',
        status: 'published',
        description:
            'The Diploma in Business Innovation & Entrepreneurship is a modern, industry-driven professional programme designed to develop innovative entrepreneurs, strategic business leaders, and globally competitive professionals capable of building sustainable businesses and leading organisational growth. It combines business administration, entrepreneurship, economics, finance, branding, digital innovation, and corporate communication into a comprehensive curriculum focused on practical execution, strategic thinking, and market relevance. Participants gain executive-level insight into business operations, innovation systems, investment strategies, leadership, and brand positioning while learning how to identify opportunities, solve business challenges, and create profitable ventures. Designed to align with global business realities and evolving market trends, the programme equips learners with the knowledge, confidence, and practical skills needed to excel in entrepreneurial, corporate, and international business environments.',
        curriculum: [
            'Module 1: Business Administration & Strategic Leadership',
            'Module 2: Entrepreneurship & Business Development',
            'Module 3: Economics, Finance & Investment Management',
            'Module 4: Corporate Communication & Brand Development',
        ],
        whoFor: [
            'Aspiring entrepreneurs and startup founders',
            'Business owners and executives',
            'Corporate professionals seeking leadership advancement',
            'Individuals interested in business innovation and digital entrepreneurship',
            'Marketing and branding professionals',
            'Business development and operations managers',
            'Financial management enthusiasts',
            'Students seeking practical business education',
            'Professionals transitioning into entrepreneurship',
            'Individuals interested in corporate communication and global branding',
        ],
        learningOutcomes: [
            {
                module: 'Module 1: Business Administration & Strategic Leadership',
                topics: [
                    'Fundamentals of Business Administration',
                    'Strategic Planning & Organisational Development',
                    'Organisational Structures & Management Systems',
                    'Business Ethics & Professional Responsibility',
                    'Financial Management Principles',
                    'Competitive Analysis & Market Positioning',
                    'Business Negotiation Techniques',
                    'Risk Management Strategies',
                    'Business Case Studies',
                    'Final Project Assessment',
                ],
            },
            {
                module: 'Module 2: Entrepreneurship & Business Development',
                topics: [
                    'Introduction to Entrepreneurship',
                    'Identifying Business Opportunities',
                    'Business Model Development',
                    'Funding & Investment Options',
                    'Digital Entrepreneurship Strategies',
                    'Legal Considerations in Business',
                    'Pitching to Investors',
                    'Scaling & Growing a Business',
                    'Entrepreneurial Case Studies',
                    'Final Business Pitch',
                ],
            },
            {
                module: 'Module 3: Economics, Finance & Investment Management',
                topics: [
                    'Introduction to Economics',
                    'Microeconomics vs. Macroeconomics',
                    'Financial Markets & Investment Systems',
                    'Business Finance & Financial Decision-Making',
                    'Financial Planning & Budgeting',
                    'Economic Policies & Global Markets',
                    'Cryptocurrency & Emerging Financial Trends',
                    'Business & Financial Risk Management',
                    'Economic Case Studies',
                    'Assessment & Evaluation',
                ],
            },
            {
                module: 'Module 4: Corporate Communication & Brand Development',
                topics: [
                    'Basics of Corporate Communication',
                    'Brand Development Strategies',
                    'Social Media & Digital Branding',
                    'Public Relations & Crisis Management',
                    'Persuasive Business Writing',
                    'Visual Identity & Design Principles',
                    'Brand Case Studies & Market Analysis',
                    'Internal & External Communication Systems',
                    'Global Branding Strategies',
                    'Final Branding & Communication Project',
                ],
            },
        ],
        certificationDetails: [
            'Diploma in Business Innovation & Entrepreneurship',
            'Entrepreneurship & Business Strategy Competency Certification',
            'Corporate Communication & Branding Recognition',
            'Practical Project Assessment Report',
            'Ashford & Gray Fusion Academy Diploma Certification',
            'Eligible: business mentorship and incubation opportunities',
            'Eligible: startup development and networking support',
            'Eligible: professional recommendation references',
            'Eligible: advanced executive business specialisation pathways',
        ],
        careerOpportunities: [
            'Entrepreneurs & Startup Founders',
            'Business Development Executives',
            'Brand & Communication Managers',
            'Corporate Strategists',
            'Business Consultants',
            'Innovation & Growth Managers',
            'Marketing & Digital Branding Specialists',
            'Financial & Investment Coordinators',
            'Public Relations Officers',
            'Corporate Communication Executives',
            'Business Operations Managers',
            'Social Media & Brand Strategists',
        ],
    },

    {
        title: 'Diploma in Event & Protocol Management',
        category: 'Diploma',
        instructor: academyBoard,
        rating: 4.9,
        reviews: 91,
        duration: 24,
        level: 'Advanced',
        price: 950000,
        currency: 'NGN',
        imageUrl: IMG.diplomaEvents,
        imageHint: 'Gala ceremony with elegant table arrangement',
        status: 'published',
        description:
            'The Diploma in Event & Protocol Management is a comprehensive professional programme designed to develop highly skilled event professionals, protocol officers, executive coordinators, and VIP service specialists capable of managing high-level events and executive engagements with precision, professionalism, and excellence. It combines event planning, protocol management, executive assistance, concierge services, VIP coordination, crisis management, and leadership support into a structured, industry-focused curriculum tailored for modern corporate, diplomatic, hospitality, and luxury service environments. Participants gain practical knowledge in event design, vendor coordination, budgeting, security management, crowd control, protocol systems, executive communication, travel coordination, and high-profile client management while developing the confidence and operational competence required to manage both local and international engagements successfully. Designed to reflect international standards and executive service expectations, the programme prepares learners for leadership roles within the fast-growing event, hospitality, protocol, and executive support industries.',
        curriculum: [
            'Module 1: Event Planning & Event Operations',
            'Module 2: Protocol, Etiquette & High-Profile Coordination',
            'Module 3: VIP Concierge & Lifestyle Management',
            'Module 4: Executive Assistance & Leadership Support',
        ],
        whoFor: [
            'Aspiring event planners and coordinators',
            'Protocol and diplomatic service professionals',
            'Executive assistants and administrative coordinators',
            'Hospitality and concierge professionals',
            'Corporate event managers',
            'Public relations and communications professionals',
            'Individuals working with high-profile clients and executives',
            'Entrepreneurs in the event and luxury service industries',
            'Government and diplomatic support personnel',
            'Professionals seeking international-standard event and protocol training',
        ],
        learningOutcomes: [
            {
                module: 'Module 1: Event Planning & Event Operations',
                topics: [
                    'Introduction to Event Planning',
                    'Venue Selection & Event Design',
                    'Vendor Coordination & Contract Management',
                    'Budgeting & Financial Planning for Events',
                    'VIP & Celebrity Event Management',
                    'Security & Risk Management',
                    'Crisis Communication Strategies',
                    'Event Marketing & Promotion',
                    'Event Execution & Coordination',
                    'Post-Event Evaluation & Reporting',
                ],
            },
            {
                module: 'Module 2: Protocol, Etiquette & High-Profile Coordination',
                topics: [
                    'Introduction to Protocol & Etiquette',
                    'Cultural Sensitivities & International Standards',
                    'High-Profile Guest Management',
                    'Crowd Psychology & Behavioural Management',
                    'Security & Emergency Protocols',
                    'Official Documentation & Briefing Systems',
                    'Crisis Handling & Decision-Making',
                    'International Protocol Procedures',
                    'Case Studies in Successful Protocol Management',
                    'Final Practical Assessment',
                ],
            },
            {
                module: 'Module 3: VIP Concierge & Lifestyle Management',
                topics: [
                    'Understanding VIP Concierge Services',
                    'Luxury Lifestyle Management',
                    'Personal Assistant Duties & Responsibilities',
                    'Exclusive Travel & Reservation Coordination',
                    'Personal Styling & Image Management',
                    'Managing High-Net-Worth Clients',
                    'Special Event Coordination',
                    'Confidentiality in VIP Services',
                    'Crisis Management in VIP Environments',
                    'Final Practical Evaluation',
                ],
            },
            {
                module: 'Module 4: Executive Assistance & Leadership Support',
                topics: [
                    'Introduction to Executive Assistance',
                    'Professional Correspondence & Business Communication',
                    'Scheduling & Time Management',
                    'Business Travel Planning',
                    'Managing Corporate Events',
                    'Leadership Support & Strategic Decision-Making',
                    'Data & File Management Systems',
                    'Presentation & Public Speaking Skills',
                    'Conflict Resolution Techniques',
                    'Final Project Assessment',
                ],
            },
        ],
        certificationDetails: [
            'Diploma in Event & Protocol Management',
            'Executive Coordination & Protocol Competency Certification',
            'VIP Service & Event Management Recognition',
            'Practical Skills Assessment Report',
            'Ashford & Gray Fusion Academy Diploma Certification',
            'Eligible: internship and placement opportunities',
            'Eligible: executive mentorship and protocol specialisation pathways',
            'Eligible: professional recommendation references',
            'Eligible: leadership development opportunities within hospitality and corporate sectors',
        ],
        careerOpportunities: [
            'Event Planners & Coordinators',
            'Protocol Officers',
            'Executive Assistants',
            'VIP Concierge Professionals',
            'Corporate Event Managers',
            'Lifestyle & Travel Managers',
            'Public Relations & Event Executives',
            'Celebrity & VIP Liaison Officers',
            'Conference & Convention Coordinators',
            'Executive Support Professionals',
            'Hospitality & Guest Experience Managers',
            'Entrepreneurs in Event & Luxury Service Industries',
        ],
    },

    // ===================================================================
    // EXECUTIVE MASTERCLASS — 3 months · ₦1,500,000
    // ===================================================================
    {
        title: 'The Silent Standard Certification Programme',
        category: 'Executive MBA',
        instructor: founder,
        rating: 5.0,
        reviews: 38,
        duration: 12,
        level: 'Advanced',
        price: 1500000,
        currency: 'NGN',
        imageUrl: IMG.silentStandard,
        imageHint: 'Minimalist luxury interior signalling discipline and order',
        status: 'published',
        description:
            'The Silent Standard Certification Programme is a premium executive-level professional development experience designed to cultivate disciplined leaders, operational strategists, hospitality professionals, executive managers, and institutional thinkers capable of delivering excellence with precision, structure, and authority. Built on the philosophy that true excellence is intentional, structured, and consistently sustained, this programme focuses on developing professionals who understand the power of systems, discipline, operational intelligence, discretion, leadership, and institutional order. The programme combines executive management principles, hospitality excellence, estate operations, leadership psychology, protocol systems, organisational governance, and strategic positioning into a transformational learning experience tailored for individuals operating within high-performance environments. Unlike conventional professional training, The Silent Standard goes beyond skills acquisition; it develops mindset, structure, operational philosophy, and long-term leadership capacity designed for modern executive, hospitality, corporate, and institutional environments.',
        curriculum: [
            'Module 1: The Foundation of The Silent Standard',
            'Module 2: Leadership & Emotional Discipline',
            'Module 3: The Architecture of Order',
            'Module 4: Anticipation & Operational Intelligence',
            'Module 5: Estate & Executive Management',
            'Module 6: Hospitality Excellence Systems',
            'Module 7: Event Command & High-Profile Operations',
            'Module 8: Institutional & Corporate Systems',
            'Module 9: From Practice to Principle',
            'Module 10: Global Positioning & Authority',
        ],
        whoFor: [
            'Hospitality and executive management professionals',
            'Estate and residence managers',
            'Executive assistants and protocol officers',
            'Corporate leaders and administrators',
            'Event and operations managers',
            'Entrepreneurs and institutional founders',
            'Professionals managing high-profile environments',
            'Individuals seeking leadership discipline and operational excellence',
            'Professionals aiming to build structured systems and executive authority',
            'Leaders interested in governance, accountability, and institutional growth',
        ],
        learningOutcomes: [
            {
                module: 'Module 1: The Foundation of The Silent Standard',
                topics: [
                    'Understanding Discipline as a System',
                    'Structure vs. Effort',
                    'Excellence vs. Performance',
                    'Developing Operational Consistency',
                    'Building Standards that Last',
                    'Professional Responsibility & Accountability',
                ],
            },
            {
                module: 'Module 2: Leadership & Emotional Discipline',
                topics: [
                    'Pressure Control & Stability',
                    'Decision-Making Under Stress',
                    'Authority Without Noise',
                    'Emotional Intelligence & Leadership Awareness',
                    'Executive Presence & Self-Control',
                    'Leadership Discipline Frameworks',
                ],
            },
            {
                module: 'Module 3: The Architecture of Order',
                topics: [
                    'Role Clarity & Organisational Alignment',
                    'Reporting Systems & Operational Communication',
                    'Command Structures & Leadership Flow',
                    'Team Coordination & Accountability Systems',
                    'Structured Operational Management',
                    'Institutional Efficiency Models',
                ],
            },
            {
                module: 'Module 4: Anticipation & Operational Intelligence',
                topics: [
                    'Predictive Service Systems',
                    'Risk Identification & Assessment',
                    'Preventive Operational Systems',
                    'Situational Awareness & Strategic Thinking',
                    'Crisis Prevention & Response Planning',
                    'Operational Intelligence Techniques',
                ],
            },
            {
                module: 'Module 5: Estate & Executive Management',
                topics: [
                    'Privacy Control & Executive Discretion',
                    'Domestic Staff Systems & Coordination',
                    'Protocol & Access Control',
                    'Executive Environment Management',
                    'Residence & Estate Operational Structure',
                    'High-Profile Client Management',
                ],
            },
            {
                module: 'Module 6: Hospitality Excellence Systems',
                topics: [
                    'Guest Experience Engineering',
                    'Service Consistency Frameworks',
                    'Hospitality Service Refinement',
                    'Luxury Service Delivery Principles',
                    'Quality Assurance & Standards Control',
                    'Reputation & Experience Management',
                ],
            },
            {
                module: 'Module 7: Event Command & High-Profile Operations',
                topics: [
                    'Event Structure & Operational Planning',
                    'Vendor Discipline & Coordination',
                    'Real-Time Event Control Systems',
                    'VIP & High-Profile Event Operations',
                    'Crisis Handling During Events',
                    'Executive-Level Event Management',
                ],
            },
            {
                module: 'Module 8: Institutional & Corporate Systems',
                topics: [
                    'Governance & Organisational Structure',
                    'Compliance & Professional Standards',
                    'Accountability Systems & Reporting',
                    'Policy Implementation Frameworks',
                    'Corporate Leadership Systems',
                    'Institutional Stability & Growth',
                ],
            },
            {
                module: 'Module 9: From Practice to Principle',
                topics: [
                    'Turning Experience into Authority',
                    'Documentation & Knowledge Systems',
                    'Legacy Framework Development',
                    'Professional Positioning Through Experience',
                    'Building Sustainable Operational Systems',
                    'Thought Leadership Foundations',
                ],
            },
            {
                module: 'Module 10: Global Positioning & Authority',
                topics: [
                    'Building Professional Influence',
                    'Executive Identity & Brand Positioning',
                    'Institutional Growth Strategies',
                    'Leadership Visibility & Credibility',
                    'Global Standards & International Relevance',
                    'Creating Long-Term Professional Impact',
                ],
            },
        ],
        certificationDetails: [
            'Certified Silent Standard Professional Certification',
            'Executive Leadership & Operational Excellence Recognition',
            'Professional Competency Assessment Report',
            'Ashford & Gray Fusion Academy Certification of Completion',
            'Eligible: executive mentorship opportunities',
            'Eligible: leadership and institutional development pathways',
            'Eligible: professional recommendation references',
            'Eligible: advanced executive specialisation opportunities',
        ],
        careerOpportunities: [
            'Executive & Estate Managers',
            'Operations & Administrative Leaders',
            'Hospitality Excellence Consultants',
            'Protocol & Executive Coordination Officers',
            'Institutional Development Strategists',
            'Corporate Operations Managers',
            'Leadership & Systems Consultants',
            'High-Profile Event & Operations Coordinators',
            'Executive Service Professionals',
            'Organisational Structure & Compliance Managers',
            'Professional Development & Governance Consultants',
        ],
    },
];

export const eventsToSeed: Omit<AppEvent, 'id'>[] = [];
