import crypto from 'crypto';
import dbConnect from './mongodb';
import LiveClass from '@/models/LiveClass';
import Enrollment from '@/models/Enrollment';
import User from '@/models/User';
import { resolveCourse } from './resolve-course';
import { sendEmail, emailTemplates } from './email';
import { getEmailUrl } from './app-url';

// Each Zoom account (primary / school) has its own Server-to-Server OAuth
// app and therefore its own webhook Secret Token, generated by Zoom when
// Event Subscriptions is turned on for that app. Two distinct webhook URLs
// (one per account) avoid ever having to guess which secret a given request
// was signed with.
export function getWebhookSecret(account: 'primary' | 'school'): string | undefined {
    return account === 'primary' ? process.env.ZOOM_PRIMARY_WEBHOOK_SECRET : process.env.ZOOM_SCHOOL_WEBHOOK_SECRET;
}

function verifySignature(rawBody: string, timestamp: string, signature: string, secret: string): boolean {
    const hash = crypto.createHmac('sha256', secret).update(`v0:${timestamp}:${rawBody}`).digest('hex');
    return `v0=${hash}` === signature;
}

/**
 * Handles a single Zoom webhook POST for one account. Returns the Response
 * to send back — url_validation must be answered inline, everything else
 * gets a bare 200 once processed (or immediately, work continues after).
 */
export async function handleZoomWebhook(account: 'primary' | 'school', req: Request): Promise<Response> {
    const secret = getWebhookSecret(account);
    const rawBody = await req.text();
    let body: any;
    try {
        body = JSON.parse(rawBody);
    } catch {
        return new Response('Invalid JSON', { status: 400 });
    }

    // Zoom's one-time endpoint validation — answered with an HMAC of the
    // plainToken it sends, using the same secret it just showed us.
    if (body.event === 'endpoint.url_validation') {
        if (!secret) return new Response('Webhook secret not configured', { status: 500 });
        const plainToken = body.payload?.plainToken;
        const encryptedToken = crypto.createHmac('sha256', secret).update(plainToken).digest('hex');
        return Response.json({ plainToken, encryptedToken });
    }

    if (!secret) {
        console.warn(`zoom webhook (${account}): no secret configured, rejecting`);
        return new Response('Not configured', { status: 500 });
    }

    const timestamp = req.headers.get('x-zm-request-timestamp') || '';
    const signature = req.headers.get('x-zm-signature') || '';
    if (!verifySignature(rawBody, timestamp, signature, secret)) {
        return new Response('Invalid signature', { status: 401 });
    }

    if (body.event === 'recording.completed') {
        try {
            await processRecordingCompleted(body.payload?.object);
        } catch (err) {
            console.error('zoom webhook: recording.completed handling failed:', err);
        }
    }

    return new Response('OK', { status: 200 });
}

async function processRecordingCompleted(object: any): Promise<void> {
    if (!object?.id) return;
    await dbConnect();

    const zoomMeetingId = String(object.id);
    const liveClass = await LiveClass.findOne({ zoomMeetingId });
    if (!liveClass) return;

    const recordingUrl: string | undefined = object.share_url || object.recording_files?.[0]?.play_url;
    if (!recordingUrl) return;

    liveClass.recordingUrl = recordingUrl;
    liveClass.recordingPasscode = object.password || object.recording_play_passcode || undefined;
    liveClass.recordingReadyAt = new Date();
    if (liveClass.status === 'scheduled') liveClass.status = 'completed';
    await liveClass.save();

    // Best-effort notification — a recording arriving late must never throw.
    try {
        const appUrl = getEmailUrl();
        const course = await resolveCourse(liveClass.courseId);
        const dashboardUrl = `${appUrl}/my-courses/${liveClass.courseId}`;

        const instructor = await User.findOne({ uid: liveClass.instructorId }).select('email displayName').lean<{ email: string; displayName: string } | null>();
        const enrollments = await Enrollment.find({ courseId: liveClass.courseId }).select('userId').lean<{ userId: string }[]>();
        const students = enrollments.length
            ? await User.find({ uid: { $in: enrollments.map(e => e.userId) } }).select('email displayName').lean<{ email: string; displayName: string }[]>()
            : [];

        const recipients = [
            ...(instructor ? [instructor] : []),
            ...students,
        ];

        for (const r of recipients) {
            if (!r.email) continue;
            const tpl = emailTemplates.classRecordingReady({
                recipientName: r.displayName || r.email,
                classTopic: liveClass.topic,
                courseName: course?.title,
                recordingUrl,
                recordingPasscode: liveClass.recordingPasscode,
                dashboardUrl,
            });
            void sendEmail({ to: r.email, subject: tpl.subject, html: tpl.html });
        }
    } catch (err) {
        console.error('zoom webhook: recording-ready notification failed:', err);
    }
}
